/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module DIG_D_FF_AS_1bit
#(
    parameter Default = 0
)
(
   input Set,
   input D,
   input C,
   input Clr,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q  = ~state;

    always @ (posedge C or posedge Clr or posedge Set)
    begin
        if (Set)
            state <= 1'b1;
        else if (Clr)
            state <= 'h0;
        else
            state <= D;
    end

    initial begin
        state = Default;
    end
endmodule

module two_bit_mux (
  input a,
  input b,
  input s,
  output y
);
  assign y = ((a & ~ s) | (b & s));
endmodule

module four_bit_mux (
  input [3:0] a,
  input [3:0] b,
  input sel,
  output [3:0] y
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  assign s4 = a[3];
  assign s5 = a[2];
  assign s6 = a[1];
  assign s7 = a[0];
  assign s8 = b[3];
  assign s9 = b[2];
  assign s10 = b[1];
  assign s11 = b[0];
  two_bit_mux two_bit_mux_i0 (
    .a( s4 ),
    .b( s8 ),
    .s( sel ),
    .y( s0 )
  );
  two_bit_mux two_bit_mux_i1 (
    .a( s6 ),
    .b( s10 ),
    .s( sel ),
    .y( s2 )
  );
  two_bit_mux two_bit_mux_i2 (
    .a( s5 ),
    .b( s9 ),
    .s( sel ),
    .y( s1 )
  );
  two_bit_mux two_bit_mux_i3 (
    .a( s7 ),
    .b( s11 ),
    .s( sel ),
    .y( s3 )
  );
  assign y[3] = s0;
  assign y[2] = s1;
  assign y[1] = s2;
  assign y[0] = s3;
endmodule

module four_bit_reg (
  input [3:0] d,
  input enable,
  input clk,
  input reset,
  output [3:0] q
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire [3:0] q_temp;
  wire [3:0] s8;
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i0 (
    .Set( 1'b0 ),
    .D( s0 ),
    .C( clk ),
    .Clr( reset ),
    .Q( s1 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i1 (
    .Set( 1'b0 ),
    .D( s2 ),
    .C( clk ),
    .Clr( reset ),
    .Q( s3 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i2 (
    .Set( 1'b0 ),
    .D( s4 ),
    .C( clk ),
    .Clr( reset ),
    .Q( s5 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i3 (
    .Set( 1'b0 ),
    .D( s6 ),
    .C( clk ),
    .Clr( reset ),
    .Q( s7 )
  );
  four_bit_mux four_bit_mux_i4 (
    .a( q_temp ),
    .b( d ),
    .sel( enable ),
    .y( s8 )
  );
  assign q_temp[3] = s1;
  assign q_temp[2] = s3;
  assign q_temp[1] = s5;
  assign q_temp[0] = s7;
  assign s0 = s8[3];
  assign s2 = s8[2];
  assign s4 = s8[1];
  assign s6 = s8[0];
  assign q = q_temp;
endmodule
